### ISSUE TITLE
Refactoring items

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#1085]
@trontrytel and I wrote down a list of some refactoring items that will help us close out #949:

#### Refactor initial conditions.
 - [x] Some of these functions in TC are currently computing auxiliary variables, which is confusing. See #1327.
 - [x] Most of the IC functions use TC internals and depend on `getindex` support, which is possible (and would be nice) to revoke. Issue opened. See #887
 - [x] We should remove the dependence on `case` types, or at least make them orthogonal to other types, and use them specifically for ICs. See #1327.
 - [x] It might make sense to split ICs into allocation + initialization, since some ICs are not in the form of point-wise functions, however, we could formulate them to be if we push the ODE solution early enough and just interpolate the solution for all z-points. Related: #1327

#### Surface
 - [x] As an incremental step, we can cache the result of `get_surface` and TC will simply unpack this surface. This will allow us to move the computation near `get_surface_fluxes!` so that we can easily debug when unifying the two types.
 - [x] Most of the surface functions use TC internals and depend on `getindex` support, which is possible (and would be nice) to revoke. Issue opened. See #887
 - [x] We need to unify `get_surface`, which has several surface types, with `get_surface_fluxes!`, it may be easier to first refactor SurfaceFluxes, which currently needs changes anyway (cc @szy21). At the very least, we should probably have a field of `SurfaceConditions`, and instead of the field of `cond_type = NamedTuple{(:shf, :lhf, :E, :ρτxz, :ρτyz), NTuple{5, FT}}`. If we refactor Surface Fluxes, then `sc = SF.Coefficients` can live inside `SurfaceConditions`, and we could dispatch on that instead of defining these `surface_args` functions, overall, the code would be cleaner and easier to unify with `get_surface`.

#### Precipitation
 - [x] We should move the precipitation computations into `src/tendencies/precipitation.jl`, and (ideally) strip out use of TC internals. This shouldn't be too difficult. See #1116, #1094
 - [ ] It would be nice (but not necessary) to inline some of the auxiliary field computations into these tendencies to reduce the number of auxiliary fields, however this involves balancing the trade-off between modularity and shared code

**Comment by szy21** [comment]
Happy to help with refactoring surface fluxes. Tapio, @akshaysridhar and me have some ideas about testing. We hope to start to work on it next week.

**Comment by trontrytel** [comment]
@dennisYatunin could you take a look here? Was all of this handled by #1327?

**Comment by charleskawczynski** [comment]
> @dennisYatunin could you take a look here? Was all of this handled by #1327?

I think so. I've opened #887 is the only necessary and unfinished piece here. Closing since we can just track that issue.
