### ISSUE TITLE
Refactor EDMF

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1104]
## Purpose
We want to refactor EDMF code in ClimaAtmos.jl. Currently EDMF is filtering based on the updraft area fraction, updraft vertical velocity and to ensure tracer positivity. We want to replace some of those filters with regularisations, change the way we handle boundary conditions, delete the unnecessary filters and move what we can to the tendency evaluation. We also want to use ClimaCore/ClimaAtmos advection operators, get rid of updraft area fraction boundary conditions and switch to using total energy in the updrafts.

## Cost/Benefits/Risks
The benefit is a better behaved scheme that can be efficiently coupled with implicit timesteppers and ClimaAtmos as a whole. The risk is that our EDMF scheme depends heavily on the filters, etc. The changes of boundary conditions and filters will most likely lead to changes of EDMF results. It would be great to know if the anticipated changes in EDMF results could be fixed by ML calibrations. However, right now we don't have a calibration pipeline hooked to TC+CA. 

## People and Personnel
- Lead: @trontrytel, @dennisYatunin 
- Collaborators: @nefrathenrici, @costachris , @szy21, @haakon-e
- Reviewers: @tapios

## Results and deliverables
 A better behaved EDMF scheme suitable for implicit single column simulations https://github.com/CliMA/ClimaAtmos.jl/milestone/4
  - All current SCM CI cases passing.
  - Non-linear filters removed, or a better understanding why they are necessary. 
  - EDMF in ClimaAtmos follows the same code patterns as ClimaAtmos.

## Task Breakdown And Tentative Due Date
- [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1103 Due Nov 11th

### CI updates
- [x] #1243 Due Jan 20th
- [x] https://github.com/CliMA/ClimaAtmos.jl/pull/1258
- [x] #1244 Due Jan 20th
- [x] #1298

### Testing EDMF IMEX simulations
- [x] #1312
- [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1351
- [x] #1380
- [x] #1385
- [ ] #1415
- [ ] Add LES profiles to CI plots

### Documentation (@tapios, @trontrytel, @szy21, @dennisYatunin)
- [x] #1397

### Setup Bomex box experiment with EDMFex (@nefrathenrici, @dennisYatunin, @trontrytel, @szy21 )
 - [x] #1464
 - [x] #1463
 - [x] #1416
 - [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1542
 - [x] #1599
 - [ ] #1600
 - [x] #1417
 - [ ] Test for momentum equations without RHS terms (bubble?)
 - [ ] Solve implicit for updraft velocities.
 - [ ] Add GABLS, Soares

### Delete update aux (@trontrytel, @dennisYatunin)
 - [x] #1418
 - [x] #1420
 - [x] #1419
 - [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1530
 - [ ] #1421

### Physics testing. (@trontrytel, @szy21)
 - [x] #1423
 - [x] #1471
 - [x] #1265
 - [x] #1422

### Calibration pipeline. (@nefrathenrici, @costachris )
 - [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1340
 - [ ] Calibratmos.jl package for a single SCM EDMF case in CA.jl - Perfect model setting.
 
### Output, diagnostics
 - [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1389 (Potentially not needed right now. Could be moved to code refactoring done for filters)
 - [ ] Improve the plotting pipeline in the CI (Plots -> Makie?)
 - [ ] EDMF relevant output from spherical runs

### Stretched grid testing
 - [ ] Check if we can have initial condition profiles that are discrete hydrostatic for SCM EDMF. (Can we use initial condition from ClimaAtmos moist baroclinic wave for this test?)
 - [ ] Add stretched grid tests for SCM EDMF. (Can we use initial condition from ClimaAtmos moist baroclinic wave for this test?)

### Backlog / known bugs
- [ ] Fix https://github.com/CliMA/ClimaAtmos.jl/issues/945 (@costachris)

### Known issues following different non-linear filters and hacks (this is related to old EDMF, not EDMFX
- [ ] Replace the LBF operators and velocity clipping by ClimaAtmos vertical_transpor. (To be used instead of gradient(LBF(Ic(CG.Wector)))). This can be done even when we are still clipping the negative velocities in EDMF.
- [ ] Refactor precipitation advection for 1-moment microphysics scheme.
- [ ] Try replacing edmf grid with ClimaAtmos coordinates.
- [ ] EDMF column loops (`real_center_indices`): Can we get rid of them? How does that affect performance.
- [ ] Specifically, can we remove EDMF's dependence on `getindex`? One of the main blockers is: #887 and  https://github.com/CliMA/ClimaCore.jl/issues/77
- [ ] What other EDMF functions can be replaced by ClimaAtmos ones? 
- [x] #1245
- [x] #1263
- [ ] #1264
- [x] #1262
- [x] #1261
- [x] #1260
- [ ] Decide what to do with the leftover filtering PRs: https://github.com/CliMA/ClimaAtmos.jl/pull/932, https://github.com/CliMA/ClimaAtmos.jl/pull/911, https://github.com/CliMA/ClimaAtmos.jl/pull/1011

## Proposed Delivery Date
...

***
## CC
@cmbengue @simonbyrne

**Comment by trontrytel** [comment]
The list is here: https://github.com/CliMA/ClimaAtmos.jl/issues/1103

**Comment by tapios** [comment]
Thank you!

**Comment by trontrytel** [comment]
Closing. The work is moved to https://github.com/CliMA/ClimaAtmos.jl/issues/1646
