### ISSUE TITLE
Add orographic drag

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#1126]
## Purpose
We would like to add the orographic drag parameterization following [Garner05](https://journals.ametsoc.org/view/journals/atsc/62/7/jas3496.1.xml?tab_body=pdf).

## Cost/Benefits/Risks
- Benefits: When we are able to run simulations with topography, it adds proper momentum dampings due to mountain drags (and will largely improve the surface pressure results -- comments from Isaac Held).
- Cost/Risks: Depending on how it is implemented, it might add more allocations and reduce performances. We will need help from software engineers (mostly likely via a separate issue).

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @jiahe23 
- Collaborators: @szy21 
- Reviewers: @LenkaNovak 

## Components
- [x] Read topography information from files;
- [x] Compute base flux;
- [x] Compute flux saturation profile;
- [x] Compute (u,v) forcings;
- [x] Hook up to ClimaAtmos infrastructure;
- [ ] Tests 
    - [ ] figure 6 in the Garner paper; 
    - [ ] reanalysis data (e.g., ERA5) which have orographic drag diagnostics - though only surface stress [here](https://apps.ecmwf.int/codes/grib/param-db/?id=195).
- [x] Interpolate topography data

## Inputs
- Theory from [Garner05](https://journals.ametsoc.org/view/journals/atsc/62/7/jas3496.1.xml?tab_body=pdf);
- Implementation following [GFDL](https://github.com/NOAA-GFDL/atmos_phys/blob/main/atmos_param/topo_drag/topo_drag.F90).

## Results and deliverables
- [x] Orographic drag parameterization that can be switch on for simulations with topography;
- [x] #1378
- [x] Documentations on the theory and our implementation.

## Task Breakdown And Tentative Due Date
- [x] Documentations on how to implement: [overleaf doc](https://www.overleaf.com/read/qhnsjtthnyvf)
- [x] ClimaAtmos infrastructure for this parameterization -- Nov 18
- [x] Read topo data (and remap if needed) -- ~Nov 22~
- [x] Implement the calculations -- ~Dec 2~
- [ ] Tests ~and documentations~ -- ~Dec 9~

## Proposed Delivery Date
Dec 9 (subject to modifications based on the progress).

***
## CC
@cmbengue @tapios @simonbyrne

**Comment by tapios** [comment]
LGTM. Please make sure that good documentation is included in the deliverables.

**Comment by jiahe23** [comment]
> LGTM. Please make sure that good documentation is included in the deliverables.

Yep, I've added it into the tasks and deliverables.
