### ISSUE TITLE
Subtract a reference state in the equations of motion

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1188]
## Purpose
Subtract a reference state of pressure and density that is in (discrete) hydrostatic balance from the equation of motion.
 
## Cost/Benefits/Risks
Benefit: As noted in the COSMO documentation, the main effect of introducing a reference state is the reduction of numerical errors associated with the calculation of the pressure gradient forcing in case of sloping coordinate systems.
Risks: It may not help with numerical instability

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @szy21 
- Collaborators: @dennisYatunin 
- Reviewers: @Zhengyu-Huang @charleskawczynski 

## Results and deliverables

- Updated equations in the code
- Benchmark simulations with the same or improved results in terms of numerical stability
- Updated design doc

## Task Breakdown And Tentative Due Date
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [ ] Construct discrete hydrostatic balance #1186 
- [ ] Write down new equations of motion and Jacobians
- [ ] Modify the explicit and implicit tendency functions

## Proposed Delivery Date
Dec 16, 2022

**Comment by tapios** [comment]
Looks fine. Equations are on Slack; modifications to Jacobian are straightforward. You can start simply by taking `p_ref = MSLP * exp(-z/H)' with `H = R_d T_ref/g` and `T_ref = 255 K`. Then compute reference density by differentiating this pressure. This should be fine for testing and give you a good indication of how much of a difference this modification makes.

**Comment by szy21** [comment]
Would it make any difference whether we construct pressure from density, or construct density from pressure?

**Comment by tapios** [comment]
For discrete balance, density from pressure is easier I think.

**Comment by szy21** [comment]
We already have pressure from density [here](https://github.com/CliMA/ClimaAtmos.jl/blob/af88e6177f24af7687c794cf5e28bd8e5e3c083c/examples/hybrid/discrete_hydrostatic_balance.jl#L42), but can do density from pressure too.
