### ISSUE TITLE
Split modifications from PR1234

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#1239]
- [x] [use weighted interpolation](https://github.com/CliMA/ClimaAtmos.jl/pull/1234/commits/3c946986bfbe5fc36e5fb8c00117783468d7df44) in #1240 
- [x] [use mass weighting of cross product in horizontal tendency](https://github.com/CliMA/ClimaAtmos.jl/pull/1234/commits/fc04e8e7c83487e8a133f4e68d2a96717b460c7a) in #1241
- [x] [change order of kinetic energy computation] https://github.com/CliMA/ClimaAtmos.jl/pull/1234/commits/a692eea652daf67b07c14b4dda2eadee8630295d in #1242

**Comment by akshaysridhar** [comment]
The combination of the PRs listed here is intended to supersede #1234.

**Comment by akshaysridhar** [comment]
@Zhengyu-Huang adding you ass an assignee just so you are aware of the work items towards splitting #1234.

**Comment by akshaysridhar** [comment]
@Zhengyu-Huang Can we close this?

**Comment by charleskawczynski** [comment]
@Zhengyu-Huang Can we close this?

**Comment by szy21** [comment]
As Daniel is not here anymore I will just close this:)
