### ISSUE TITLE
ClimaAtmos.jl folder restructuring plan

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaAtmos.jl#1383]
### Purpose
We need a clean and simple code structure for ClimaAtmos.jl that is not to dissimilar from conventional already existing climate models. File and folder naming conventions need to reflect this. In addition, we want that the code functions like a collection of libraries that can easily be extended. This issue complements the testing issue #1328. The goal is to have the equations of motion be localized and extended by various right-hand side and left-hand-side terms that can be toggled on and off and that live in easy to find and change places in the code.

As guiding examples we will use the NOAA-GFDL models' source code as well as the Oceananigans.jl source code (see references).

### Cost/Benefits/Risks
**Costs**: 
Several developer/scientist days/weeks

**Benefits**:
Clean and recognizable code structure for internal and external contributors. Streamlined documentation that reflects current state of the code.

**Risks**:
Disruption of concurrent development efforts and hence delays of other ClimaAtmos.jl deliverables. The aim of this plan is to minimize this risk as much as possible to not incur **unnecessary** delays. However, some delays due to restructuring may be inevitable.

In order to mitigate these risks, we plan on first restructuring the folder structure on a series of PRs without renaming functions. This way rebasing existing work streams remains easy. After that, we will restructure some functions in a series of small PRs to keep the rebasing burden low.

### People and Personnel
- Lead: @bischtob 
- Collaborators: @akshaysridhar 
- Reviewers: @simonbyrne, @szy21 

### Components
**Part 1 (new file & folder structure)**
We aim to reorganize the files and folder structure to reflect a common climate model and to be similar to Oceananigans.jl's code structure.The following sketch shows the plan
```
src
     - prognostic_equations
         - staggered_nonhydrostatic_model.jl
         - edmf.jl
         - implicit.jl
         - ...  
     - tendencies
          - gravity_wave
              - file1.jl
              - file2.jl
              - ....
          - radiation
              - file1.jl
              - file2.jl
              - ....
          - ...
     - utils
     - shared
     - ...
test 
     - prognostic_equations
         - test_cool_thing1.jl
         - ...
     - tendencies
          - test_cool_thing2.jl
         - ...
     - utils
         - test_a_util.jl 
     - shared
     - ...
validation 
     - driver1.jl
     - driver2.jl
     - ...
     - utils_val.jl
examples 
     - driver99.jl
     - driver98.jl
     - ...
     - utils_examples.jl
performance
     - driver1.jl
     - ...
     - utils_perf.jl
```
The steps that need to be taken are outlined in details below and are aimed at minimizing renaming of functions for now. The end of Part 1 of this plan is a rewrite of our docs that reflect the new structure and the state of the code.

**Part 2 (dycore equations reorganizations without EDMF)**
We aim to rearrange dycore equations to achieve the following requirements:

- Equations of motion are in one place
- Have a flag for topography which modifies the equations of motion
- Right-hand side terms are clearly separated (for adding parameterizations without prognostic variables)
- Can run single column model by setting horizontal velocities to 0 (setting states or tendencies to 0)
- Keep EDMF separated in first iteration and asses EDMF needs afterwards

### Inputs
Current ClimaAtmos.jl codebase and documentation.

### Results and deliverables
We'll have a new directory structures with clean layout. In addition, we'll have localized dycore equations and add-ons, such as parameterizations, will live in their own library folders. Testing and validation will be cleanly separated with driver files for each experiment. Docs will be streamlined to reflect changes.

### Task Breakdown And Tentative Due Date*
**Part 1**
This part is mostly about changing the folder structure in a series of small PRs. After these tasks are done, we should have a more organized grouping of files.
- [x] #1424
- [x] #1425
- [x] #1426
- [x] #1427

**Part 2**
This part is mostly concerned about reorganinzing the internals of the dycore source code within the new src directory to reflect requirements for code locality.
- [x] Add topography flag that toggles equation modification
- [x] Add single-column flag that toggles equation modification
- [x] #1663
- [x] #1664
- [x] Update docstrings and comments where necessary
- [x] #1399

### References
[NOAA-GFDL Climate Models](https://github.com/NOAA-GFDL/AM4/tree/main/src)
[Oceananigans.jl](https://github.com/CliMA/Oceananigans.jl)

***
### Metadata
- Proposed by: @bischtob, @szy21 
- Proposal date: 
- Approved by: 
- Approval date: 

### CC
@tapios, @cmbengue, @simonbyrne

**Comment by jiahe23** [comment]
Thanks for drafting out this SDI. 

One thing I think we need to do at some point is to structure a simpler but more flexible way of specifying parameters related to each physical processes. This is also related to the restructuring but is definitely not the low hang fruit.

For example, the bulk formula coefficient used in the surface flux calculation is currently a cli optiton. We could test different values by changing it in command line. Same as the parameters for the rayleigh sponge layer. This strategy works fine if we only have a few numbers of physical processes with very few parameters each.

On the other hand, the gravity wave parameterization has more than ten parameters and it is insane to put them all in the cli, the way we do it is to create the struct and prescribe the values in the model_getter, which means we will have to change the source code in order to test different parameter combinations.

In addition, when testing with different setups, we want some simple way to save the parameters for the simulation.

**Comment by szy21** [comment]
Thanks @jiahe23. We didn't plan to change the parameters because it will be done [here](https://github.com/CliMA/ClimaAtmos.jl/issues/1259). I'm not sure exactly what the timeline is though.

**Comment by bischtob** [comment]
@akshaysridhar, let's put your thoughts from our conversation today in here.

**Comment by akshaysridhar** [comment]
Recalling this morning's discussion:

(1) Right now a "driver" would basically be a SLURM script with a specific set of command line arguments, this is helpful if we are already familiar with the complete list of cl-options; I agree with @jiahe23 that these might become unwieldy at some point (It seems this is not part of Part (1) of the interface upgrade effort so we can keep it in mind for now); We'd talked this morning about making these argument groupings more readable through TOML (or similar) files, while retaining the info statements that summarize "active" tendencies and forcings.

(2) Following (1) then, maybe it would useful to define a separate issue to commit to exactly what we want to define as a "driver", 
- what level of interaction with physics components do we want the user to have
- how easy is it to run a prototype experiment from the REPL and explore ideas
- would there be template drivers for different "groups" of experiments?
- with numerous available drivers, it would be useful to have wrapper functions that summarize the main driver behaviour (so a user can choose the best place (perhaps an existing validation experiment) to start when developing new experiments.  
- clear list of default parameters and driver options would be helpful in the docs (we have this to some extent in the cl-args documentation now).  
- regarding reproducibility we have the complete `env` log within the buildkite so it would be great to retain this in some form.

**Comment by bischtob** [comment]
@simonbyrne, @trontrytel, @valeriabarra please chime in here. Please pay special attention to our unique parameterizations (EDMF) as they are adding additional dycore equations.

**Comment by bischtob** [comment]
@tapios, dycore -> prognostic equations and parameterizations -> parameterized_tendencies. Put Held Suarez as radiation parameterization.

**Comment by trontrytel** [comment]
I'll come back here next week after we take stock of the equations written by @tapios, the current EDMF code structure and the desired code structure. 

Having a good plan of where we want to put  EDMF equations in the ClimaAtmos code will help in planning the refactoring of the EDMF code itself.

**Comment by trontrytel** [comment]
And also, @nefrathenrici is working on replacing most of the CLI arguments with toml files, starting with SCM EDMF cases. It would be good to sync so that the two restructuring efforts are pushing in the same direction.

**Comment by simonbyrne** [comment]
a few minor comments:
- I think the amount of Julia code in non-`src` directories should be absolutely minimal e.g. 
  - argument and toml parsing functions should be defined in `src/driver`
  - postprocessing should be in `src/postprocessing`
- a good place to find low-hanging fruit is to look at places where we `include` a file from a different directory (as a general rule, this means it should go in `src` and be loaded by `using ClimaAtmos`), e.g.
https://github.com/CliMA/ClimaAtmos.jl/blob/cf587448e729604cef8d274641a0d4ad54c8d572/test/orographic_gravity_wave/ogwd_baseflux.jl#L10-L12
https://github.com/CliMA/ClimaAtmos.jl/blob/86ac9ac66ecb5c4aa76d787fcaa8aed73babe8f1/examples/hybrid/parameter_set.jl#L3
https://github.com/CliMA/ClimaAtmos.jl/blob/e195844149e954e1b35e1c95375e42f58e81ba62/test/non_orographic_gravity_wave/nogw_test_3d.jl#L55

**Comment by bischtob** [comment]
cc @szy21 :)

**Comment by szy21** [comment]
I think it's also hard for me to predict what to do in Part 2 before we know what the code looks like after Part 1 is done. What you currently have looks good to me.

**Comment by jiahe23** [comment]
Shall we also move post_processing into src in Part 1? This makes the remap functionality easier to use but needs to add the dependencies on ClimaCoreTempestRemap

**Comment by bischtob** [comment]
@szy21 what do you think?

**Comment by szy21** [comment]
Charlie doesn't want `ClimaCoreTempestRemap` in the dependencies, and that's why post processing and some other tests are not in `src/`. I don't have a preference, but don't know exactly why it is not a good idea to have `ClimaCoreTempestRemap`.

**Comment by charleskawczynski** [comment]
> Charlie doesn't want `ClimaCoreTempestRemap` in the dependencies, and that's why post processing and some other tests are not in `src/`. I don't have a preference, but don't know exactly why it is not a good idea to have `ClimaCoreTempestRemap`.

Maybe we can do the post processing last (and hope that Julia 1.9 has been released) since precompilation with Makie / Plots is pretty long. I'm fine with moving this in eventually, though

**Comment by charleskawczynski** [comment]
Superseded 426

**Comment by bischtob** [comment]
@trontrytel suggests nightly reports :)_
This looks great! A couple of (late) comments:

    For EDMF it has worked really well to include the current main branch and the PR branch in the same plot that is shown as artifact in a given builkite job. This is especially useful when combined with some simple regression tests. Then the workflow is:
    (i) regression tests flag the CI cases where PR results are at all different than the stored reference data,
    (ii) the reviewer/developer knows which cases to check,
    (iii) plots with main vs PR branch make it easy to decide if the resulting changes are insignificant, significant and good, or significant and bad.
    The key thing is to make it easy to update the reference data, so that we are not afraid to make changes to the simulation results.
    I really liked when the nightly runs in the old ClimateMachine repo were posting the resulting plots on Slack. This was the easiest way for me to remember to keep paying attention to the long run builds and quickly catch when my simulations break.
    👍 for some standard plotting pipeline for all our cases.
Can we use YAML.jl to produce an automated buildkite summary of sorts ? Something we could perhaps store and verify in docs at a glance? MWE with the basic functionality from YAML.jl looks something like this for a specific group :

julia> data = YAML.load_file(".buildkite/pipeline.yml"; dicttype = OrderedDict{String,Any})
julia> for ii = 1:length(data["steps"][5]["steps"][:])
           @info data["steps"][5]["steps"][:][ii]["label"];
       end
[ Info: :computer: single column hydrostatic balance float64
[ Info: :computer: single column radiative equilibrium gray
[ Info: :computer: single column radiative equilibrium clearsky
[ Info: :computer: single column radiative equilibrium allsky idealized clouds varying insolation
[ Info: :computer: single column non-orographic gravity wave parameterization

i.e. here perhaps we just filter "groups" or "labels" ; given data is tied to the existing version of buildkite pipeline, this should auto-update each time we add/remove a label
with the current structure I guess the entire test (even better if the buildkide setup already provides this functionality) list dumped looks like

for jj = 4:13 # Assumes we have some pre-test and post-test jobs, remove hardcoded indices
       for ii = 1:length(data["steps"][jj]["steps"][:])
                  @info data["steps"][jj]["steps"][:][ii]["label"]
       end
end

Would be great to also allow the reference state to be zero in the regression tests. See here: https://github.com/CliMA/ClimaAtmos.jl/pull/1475
