### ISSUE TITLE
Couple NOGW with Convection parameterizations

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaAtmos.jl#1558]
# The Climate Modeling Alliance
### Purpose
Right now, sources for non-orographic gravity wave (NOGW) is prescribed as function of latitudes. We would like to add an option that allows for the source being computed directly from convection heating profiles.

### People and Personnel
- Lead: TBD
- Collaborators: TBD
- Reviewers: TBD

### Components
**Part 1 (Code restructure and optimization)**
The NOGW source specification need to be separated out so that it can be easily switched between a prescribe profile or a convective heating determined profile; some known unresolved code structure issues (#897) may need to be resolved for a better performance.

**Part 2**
Implement and test the convective heat induced GW sources following [Beres04](https://journals.ametsoc.org/view/journals/atsc/61/3/1520-0469_2004_061_0324_amostg_2.0.co_2.xml) and WACCM6 codes.

**Part 3**
Couple the source computation with existing convection scheme (i.e., EDMF) and test in SCM and GCM set-ups. -> This will definitely create bizarre results in the first several runs and may need a whole separate SDI for testing/calibrating. 

### Inputs
[Beres04](https://journals.ametsoc.org/view/journals/atsc/61/3/1520-0469_2004_061_0324_amostg_2.0.co_2.xml) and WACCM6 codes

### Results and Deliverables
We will be able to specify whether to run NOGW from prescribed or convective heating induced sources. 

### Task Breakdown And Schedule
**Part 1**
- [ ] Separate out source specification from wave propagating/breaking in the NOGW function;
- [ ] Use `Fields` rather than arrays in NOGW functions, and pass colidx into args (may also apply to OGWD);
- [ ] Reduce unnecessary allocations;

**Part 2**
- [ ] Implement source spectra computation and test following [Beres04](https://journals.ametsoc.org/view/journals/atsc/61/3/1520-0469_2004_061_0324_amostg_2.0.co_2.xml);

**Part 3***
- [ ] Couple the source computation with EDMF;
- [ ] Test the coupled setup in SCM;
- [ ] Set up GCM simulations with NOGW using convective heating and test towards [Beres05](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2004JD005504).

### CC
@tapios @simonbyrne @cmbengue

**Comment by tapios** [comment]
Looks like a good plan. But shouldn't this wait until after the EDMF scheme is working?

**Comment by jiahe23** [comment]
> Looks like a good plan. But shouldn't this wait until after the EDMF scheme is working?

We could work on the first two parts without EDMF:
- Part 1 is to restructure and optimize the current NOGW functions so that source specification can be easily switched between prescribed or convective heating induced momentum flux spectra.
- Part 2 is to implement the computation and test with prescribed heating profile.

With these 2 parts done (roughly in 1-2 month's depending on the priority and how much time being spent here), hopefully we could have some working examples of EDMF in SCM setup, that can be used to prototype the coupling, as listed in Part 3.

**Comment by tapios** [comment]
Sounds good. Let's discuss priorities though--this can wait a bit if needed.
