### ISSUE TITLE
EDMFX diagnostic and explicit

### ISSUE THREAD

**Issue by trontrytel** [CliMA/ClimaAtmos.jl#1646]
### Purpose
- Implement physics closures in EDMFX and run explicit simulations.
- Implement diagnostic EDMFX.

### Cost/Benefits/Risks
- Cost: Not having EDMFX costs us dearly.
- Benefit: This is required before working on implicit EDMFX.
- Reducing risk: Diagnostic EDMFX is our backup for implicit EDMFX.

### People and Personnel
- Lead: @trontrytel 
- Collaborators: @dennisYatunin @nefrathenrici @szy21 @jiahe23 @costachris 
- Reviewers: @tapios 

### Components
- Part 1: [Implement physics closures in EDMFX](https://github.com/CliMA/ClimaAtmos.jl/issues/1421)
- Part 2: Implement diagnostic EDMFX
- Part 3: Reproduce the canonical single column cases for diagnostic and explicit setups. 

### Inputs
- Re-use as much as possible of the old EDMF closures (`update_aux`, etc).
- Documentation of solved equations in overleaf and numerics in ClimaAtmos docs.
- Calibration pipeline for calibrating EDMFX in ClimaAtmos.jl.
- Turbulence/convection science support in making the simulations stable.

### Results and Deliverables
- Simulations reproducing single column canonical cases that we have in the CI (Bomex, Dycoms, etc)
- A spherical moist baroclinic wave simulation that can be run for a couple of steps with EDMFX.
- Documentation added to [ClimaAtmos docs](https://clima.github.io/ClimaAtmos.jl/dev/edmf_equations/) 

### Milestones
- [ ] Run the prognostic edmf explicitly for bomex, dycoms, and rico
- [ ] Run the prognostic edmf explicitly on the sphere
- [ ] Run the diagnostic edmf (with TKE equation) explicitly for bomex, dycoms, and rico
- [ ] Run the diagnostic edmf explicitly on the sphere
- [ ] Run the diagnostic edmf with implicit vertical diffusion on the sphere (?)

#### Part 1: Implement physics closures (@trontrytel, @dennisYatunin)
 - [ ] #1421 :
 - [x] non-hydrostatic pressure
 - [x] buoyancy
 - [x] subdomain buoyancy exchange term
 - [ ] shear
 - [x] saturated/unsaturated gradients
 - [x] buoyancy gradients
 - [x] mixing length
 - [ ] microphysics
 - [x] SGS fluxes to the grid mean

#### Part 2: Implement diagnostic EDMFX (@szy21 , @jiahe23)
- [x] Write equations documentation for diagnostic EDMFX
- [x] #1722  
- [x] #1655
- [x] #1724 
- [ ] #1800 
- [x] #1806 
- [x] #1743
- [x] #1896
- [x] #1897
- [x] #1840 

#### Part 3: Simulations 
- [ ] Bomex
- [ ] GABLS
- [ ] Soares
- [ ] Dycoms
- [ ] Rico
- [ ] TRMM
- [ ] Nieuwstadt
- [ ] lifecycle
- [ ] spherical moist baroclinic wave

#### QA and testing (@jiahe23 , @szy21 , @trontrytel )
- [ ] #1600
- [ ] Test for momentum equations (without RHS terms?) in a bubble setup.
- [ ] Add LES profiles to CI plots

#### Calibration pipeline. (@nefrathenrici, @costachris )
 - [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1340
 - [ ] Calibratmos.jl package for a single SCM EDMF case in CA.jl - Perfect model setting.

**Comment by szy21** [comment]
Superseded by #1974 (and other SDIs to be opened).
