### ISSUE TITLE
Remaining issues and tests for explicit diagnostic EDMF

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1950]
Here is a list of what we still need to add or check for diagnostic EDMF:
- Closures
  - [ ] Fix the closures with topography (it should always use z - z_sfc)
  - [ ] Add nonhydrostatic pressure drag #1800 
  - [x] Add prandtl number calculation #1955 
  - [ ] Use pi group entrainment and detrainment
  - [ ] Fix the shear term (right now it is not accurate with topography or stretched grids)
  - [ ] Check physical vertical velocity used in closures
- SGS fluxes
  - [ ] Add diffusion for vertical velocity #1859 
  - [ ] Add momentum mass flux #1736 
- Cloud diagnostics
  - [ ] Add covariance calculation #1909 
  - [ ] Add other cloud diagnostics (e.g. q_liq, q_ice)
- Documentation
 
Here is a list of physical tests we want to have:
- Box
  - [x] Bomex
  - [x] Dycoms
  - [ ] Rico
  - [x] Stable boundary layer #1960 
  - [ ] TRMM #1957 
  - [ ] Add LES comparison
- Sphere
  - [ ] Aquaplanet with clear-sky radiation and zonally symmetric SSTs
  - [ ] Aquaplanet with clear-sky radiation and zonally asymmetric SSTs
  - [ ] Aquaplanet with all-sky radiation and zonally symmetric SSTs
  - [ ] Aquaplanet with all-sky radiation and zonally asymmetric SSTs
  - [ ] Aquaplanet with all-sky radiation, zonally symmetric SSTs and topography
  - [ ] Aquaplanet with all-sky radiation, zonally asymmetric SSTs and topography

**Comment by szy21** [comment]
Superseded by #1974 and other SDIs.
