### ISSUE TITLE
O1.5.1a Run explicit diagnostic EDMF for canonical test cases in a box

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1974]
# The Climate Modeling Alliance
### Purpose

Demonstrate that diagnostic EDMF scheme captures key cloud regimes (GABLS, BOMEX, DYCOMS, RICO, TRMM LBA) with explicit timestepping

### People and Personnel

- Lead: @szy21 
- Collaborators: @trontrytel @dennisYatunin 
- Reviewers: @tapios 

### Results and Deliverables

- Box simulations comparable to LES and old EDMF

### Task Breakdown And Schedule

```[tasklist]
### Closures
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2028
- [ ] #1800
- [x] #1955
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1994
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1985
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2003
```

```[tasklist]
### Box test cases
- [x] Bomex
- [x] Dycoms
- [x] Rico
- [ ] #1960
- [ ] #1957
```

### CC
@tapios @simonbyrne @cmbengue

**Comment by szy21** [comment]
All the test cases have been added to ci, under `EDMFX`, see the latest [build](https://buildkite.com/clima/climaatmos-ci/builds/12564) for example.

In summary, DYCOMS and GABLS look good. TRMM looks ok although the area fraction is too small. Bomex and Rico look noisy. The results are likely due to an idealized entrainment and detrainment closure. We think the results are good enough to show that we have explicit diagnostic edmf working for box test cases. I have moved the remaining tasks to #1975, as some of them are less important for now, or depend on other milestones (implicit solver and covariant derivative). I will close this SDI and milestone after the last task is closed.
