### ISSUE TITLE
O1.5.1c Run implicit diagnostic EDMF for canonical test cases in a box

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#1975]
# The Climate Modeling Alliance
### Purpose

Demonstrate diagnostic EDMF scheme with implicit (JFNK with preconditioner) timestepping for diffusion terms in grid-scale equations (GABLS, BOMEX, DYCOMS, RICO, TRMM LBA)

### People and Personnel

- Lead: @szy21 
- Collaborators: @dennisYatunin @trontrytel 
- Reviewers: @tapios 

### Task Breakdown And Schedule

```[tasklist]
### Implementation
- [x] Check physical vertical velocity used in closures
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2027
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1986
- [ ] #1880
- [ ] #2397
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2055
- [ ] #2110
```

```[tasklist]
### SGS fluxes
- [ ] #1859 
- [ ] #1736 
```

```[tasklist]
### Documentation
```

```[tasklist]
### Test cases
- [x] Bomex
- [x] Dycoms
- [x] Rico
- [x] GABLS
- [x] TRMM
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2033
```
```[tasklist]
### Miscellaneous
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2267
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2347
```

### CC
@tapios @simonbyrne @cmbengue

**Comment by szy21** [comment]
All the box test cases are run stably with implicit diffusion with 200 secs timestep. The simulations have been added to ci. I think we can close this issue. The remaining tasks are not important for now, and I will move them to the next milestone.
