### ISSUE TITLE
Tune GPU performance for AMIP simulations

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaAtmos.jl#1995]
# The Climate Modeling Alliance
### People and Personnel
 @simonbyrne 

### Task Breakdown And Schedule
- [ ] [GPU performance improvements to `ClimaCore.jl`](https://github.com/CliMA/ClimaCore.jl/issues/1428)
- [ ] `ClimaAtmos.jl`
  - [ ] Add QA benchmarks for target AMIP simulations
  - [ ] Asynchronous kernel launches using CUDA streams
  - [ ] Move model-cache variables to fully typed structs
  - [ ] Add grid-dependent hyperviscosity specification
  - [ ]  Balance model-cache recomputation and computing on-the-fly cache
  - [ ] Evaluate and tune interfaces to component multiphysics codes/modules (Radiation, Land, etc.)

**Comment by simonbyrne** [comment]
Focus on RRTMGP
