### ISSUE TITLE
O1.5.2a High-top, multi-year atmosphere simulations resolution

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#2002]
# The Climate Modeling Alliance
### Purpose
This is the tracking SDI associated with ClimaAtmos OKR milestone **1.5.2a** (high-top, multi-year atmosphere simulations). 

### Cost/Benefits/Risks
Wall-time requirements for tuning of parameters (Rayleigh-sponges / viscous-sponges / hyperviscosity). Risk can be mitigated by automating these runs through configuration files, and by using the ClimaAtmos checkpoint+restart system. 

### People and Personnel
 @szy21 @LenkaNovak @sriharshakandala 

### Results and Deliverables
Configuration files (linked to the automated buildkite testing pipeline) corresponding to each of the required high-top atmosphere configurations.

```[tasklist]
### Task Breakdown And Schedule
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1990
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1991
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1992
```

### CC
@tapios @simonbyrne @cmbengue @szy21

**Comment by szy21** [comment]
Thanks Akshay. Let's only track O1.5.2a here and open a new one for O1.5.2c (some other physical component may be required there).

**Comment by szy21** [comment]
For vertical resolution, let's start with this: `z_max: 55000.0 z_elem: 63 dz_bottom: 30.0 dz_top: 3000.0`. This gives the following grid:
```
[15.0, 51.3547, 100.577965, 162.99532, 238.94705, 328.78918, 432.8943, 551.65234, 685.4711, 834.7763, 
1000.0111, 1181.6357, 1380.1261, 1595.9731, 1829.6814, 2081.7686, 2352.7646, 2643.211, 2953.6616, 3284.6824, 
3636.8528, 4010.766, 4407.032, 4826.2783, 5269.1514, 5736.32, 6228.4785, 6746.3496, 7290.687, 7862.2803, 
8461.957, 9090.592, 9749.104, 10438.471, 11159.73, 11913.984, 12702.412, 13526.275, 14386.932, 15285.838, 
16224.569, 17204.83, 18228.469, 19297.5, 20414.117, 21580.734, 22799.99, 24074.805, 25408.402, 26804.367, 
28266.703, 29799.887, 31408.97, 33099.664, 34878.48, 36752.87, 38731.438, 40824.18, 43042.83, 45401.266, 
47916.094, 50607.438, 53500.0]
```

The setup we can tune is:

- Where the rayleigh sponge starts (zd_rayleigh): Try to make it higher than 35km.
- Where the viscous sponge starts (zd_viscous): Try to make it higher than 35km.
- Rayleigh sponge coefficient for vertical velocity (alpha_rayleigh_w)
- Viscous sponge coefficient (kappa_2_sponge)
- Please set Rayleigh sponge coefficient for horizontal velocity (alpha_rayleigh_uh) to zero. The default is not zero.
- Small changes in hyperviscosity (kappa_4) and divergence damping (divergence_damping_factor) are ok.

@tapios Does this look ok to you?

**Comment by tapios** [comment]
Looks good. The Rayleigh damping of horizontal velocities must be zero.

**Comment by szy21** [comment]
And for each simulation, please make the following plots when available (This would be in general what we want to look at, I can move the list somewhere else later, let me know if there is any question):

- lat-pressure or lat-z plots of zonal mean zonal wind, vertical velocity, temperature, specific humidity, and relative humidity
- lat-lon plots of sensible heat flux, latent heat flux at the surface, and lat-lon plots of net shortwave and longwave radiative fluxes at the surface and top of the atmosphere.
- line plots of zonal mean precipitation, evaporation, sensible heat fluxes, and latent heat fluxes at the surface

If the simulation becomes unstable, we can talk about what to look at in more detail.

**Comment by szy21** [comment]
> Looks good. The Rayleigh damping of horizontal velocities must be zero.

Sounds good. In that case @akshaysridhar would you mind opening a PR to set the default to zero?

**Comment by akshaysridhar** [comment]
@szy21 draft PRs for each of the listed issues are up - I'm launching them on standard slurm queue with the newer nodes to avoid blocking buildkite resources for now.

**Comment by szy21** [comment]
The simulations have been added to longrun buildkite, and run offline for 1000 days. The results look good. I think we can close this SDI and milestone. Thanks @akshaysridhar!
