### ISSUE TITLE
O3.2.1: Clean Up Parameters

### ISSUE THREAD

**Issue by nefrathenrici** [CliMA/ClimaAtmos.jl#2030]
# The Climate Modeling Alliance
### Purpose

We need to get the repo ready for calibration, which mainly means cleaning up the parameters. This will be done by cleaning up hardcoded values and ensuring that no parameter values are being set outside the intended climaparameters flow.

### Cost/Benefits/Risks

There is no significant risk beyond developer time, but this needs to be done before we continue with calibration.

### People and Personnel

TBD

### Components
- [Remove parameters from config](https://github.com/CliMA/ClimaAtmos.jl/issues/2020): There are a couple parameters which some CI runs set via the config. These need to be placed in TOML files instead. This will be the quickest to accomplish.
- [Unify Parameter sets](https://github.com/CliMA/ClimaAtmos.jl/issues/1199): Currently `create_parameter_set()` overrides some parameters depending on the configuration. The preferable solution is to unify this into one parameter set that minimizes the simulation results. I expect that this will take some time, since I need to make sure that none of the tests are crashing with the single parameter set.
- [Remove hardcoded values](https://github.com/CliMA/ClimaAtmos.jl/issues/1989): @odunbar has catalogued a lot of the hardcoded parameters. To remove them, we need to add them to climaparameters and support their use in the model. This will be split into a couple smaller PRs. This may be difficult as some hardcoded values aren't really physical parameters but seem to be workarounds to improve simulation stability.
- Stretch: Simplify the parameter flow and clean up the ClimaAtmosParameter struct. This is a final goal that isn't strictly necessary, but would likely save time for the future.
### Results and Deliverables
A unified parameter interface which can be altered only by a toml file as specified in the ClimaParameters docs.

### Task Breakdown And Schedule

- [x] Remove parameters from config - Fri 9/1/23
- [x] Remove hardcoded values - Fri 9/8/23
- [x] Unify parameter sets - Fri 9/8/23
- [x] Stretch: 9/15/23

### CC
@tapios @simonbyrne @cmbengue

```[tasklist]
### Active Work
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/2017
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/2021
```

**Comment by tapios** [comment]
Thanks, @nefrathenrici. This looks good to me.
