### ISSUE TITLE
O1.5.2d Run AMIP simulation with 0M microphysics

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2240]
# The Climate Modeling Alliance
### Purpose

Demonstrate stable multiyear simulations with Earth topography in an AMIP configuration with simple land model. The atmosphere physical process should include time-varying insolation, all-sky radiation with correct cloud diagnostics, Monin-Obukhov surface fluxes and 0M microphysics.

### People and Personnel

- Lead: @akshaysridhar  
- Collaborators: @szy21 @LenkaNovak @kmdeck 
- Reviewers:

### Results and Deliverables

- [ ] Aquaplanet simulation with topography
- [ ] AMIP simulation

### Task Breakdown And Schedule
```[tasklist]
### Topography
- [ ] #1786
- [ ] #1846
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2014
- [ ] Verify longrun configuration with 1M microphysics
```

### CC
@tapios @simonbyrne @cmbengue
@akshaysridhar Please add details. Also feel free to create a corresponding SDI in ClimaCoupler.

**Comment by tapios** [comment]
We want this to be in the target vertical resolution (64 levels, tall domain, >50 km), but it can be at coarse horizontal resolution (~200 km). Also, the end point should be a run on GPUs.
