### ISSUE TITLE
O1.5.3c Run AMIP with diagnostic EDMF and simple land model

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2493]
# The Climate Modeling Alliance
### Purpose

Demonstrate a stable AMIP simulation with diagnostic EDMF.

### Task Breakdown And Schedule

```[tasklist]
### Implementation (WIP)
- [ ] #2478 
- [ ] #2479 
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2498
```

```[tasklist]
### Test cases
- [x] Aquaplanet: diagnostic EDMF + 0M + clear-sky radiation
- [x] Aquaplanet: diagnostic EDMF + 0M + all-sky radiation
- [ ] Aquaplanet: diagnostic EDMF + 1M + all-sky radiation
- [ ] Aquaplanet: diagnostic EDMF + 1M + all-sky radiation + topography
- [x] AMIP: diagnostic EDMF + 1M + all-sky radiation
```

### CC
@tapios @simonbyrne @cmbengue

**Comment by szy21** [comment]
AMIP with diagnostic EDMF has been added to the coupler longrun. Several improvements can be made and there are instability issues, which are not the current focus and will be tracked separately.
