### ISSUE TITLE
Performance roadmap

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#2632]
This issue is a continuation of #635, but I'm excluding the items we've addressed, and adding more relevant updates.

## Key items to tackle

 - [ ] Improve RRTMGP performance (https://github.com/CliMA/RRTMGP.jl/issues/389 seems important)
 - [ ] GC pauses can happen at different places on different processes, which will hamper scaling efficiency (as processes will wait for other processes running GC): once we've reduced allocations we can disable the GC and trigger it manually intermittently. `GC.enable(false)` and `GC.gc()` to trigger manually
 - [ ] We still communicate whole elements instead of just boundaries: this will require a bit of work in ClimaCore, but we'd like to see hard numbers before going down this route. @sriharshakandala, have we resolved this bullet?
 - [ ] Use `*` over `/` if not being optimized **low impact, very little effort**
 - [ ] Measure performance of new diagnostics. We've added a callbacks flame graph, which shows time spent during diagnostics, but we should use more realistic parameters, like resolution and frequency of different diagnostics.
 - [x] Use sparse mat-mul operations for AxisTensor conversions. See PR https://github.com/CliMA/ClimaCore.jl/pull/853. We need to make sure that, on a similar note, that loading the local geometry isn't having a huge impact on our kernels. **Medium to high impact, large effort**
 - [ ] Add capability to fuse operations. Fusing operations would allow us to increase the arithmetic intensity of our kernels, enabling us to reach higher peak performance (as we are likely bandwidth bound). **Moderate to high impact, moderate to large effort**
 - [ ] Specialize on GPU performance of basic FieldVector broadcast expressions. I recently saw the timestepper portion of a Nsight systems report and realized each fieldvector broadcast expression is launching at least two kernels (cell center and cell face). Often these are just copy-to, or simple add/sub/mul/div against Real, and we can likely specialize to launch a single, perhaps more optimized kernel than what we're currently generating. I don't think we have any benchmarks for FieldVector BC expressions. This is actually reasonably low hanging fruit in that everything can happen in ClimaCore, and we may even be able to fix the performance issues we see in Krylov.jl. **Moderate impact, small to moderate effort**

## Performance notes / specs

 - I've excluded the items for: time stepper LU factorization, impact of loops over mesh components. I explained why in #635.

Nsight report for p100 Dyamond simulation:

![image](https://github.com/CliMA/ClimaAtmos.jl/assets/1880641/c6b5a531-47c8-496b-924a-a7c77778c5af)

**Comment by charleskawczynski** [comment]
Alright, here is the prototype example for multi-broadcast loop fusion.

```julia
#=
include(joinpath("..", "perf", "multi_bc_example.jl"))
include("multi_bc_example.jl")
=#
using Revise
import BenchmarkTools

struct CPU end
struct GPU end
device(x::Array) = CPU()
device(x) = GPU()

function copyto_cpu!(pairs::T) where {T}
    @inbounds for i in eachindex(first(pairs).first)
        knl_rcopyto!(pairs, i)
    end
    return nothing
end

Base.@propagate_inbounds function knl_rcopyto!(pair, idx)
    dest,src = pair.first, pair.second
    @inbounds dest[idx] = src[idx]
    return nothing
end
Base.@propagate_inbounds function knl_rcopyto!(pairs::Tuple, idx)
    knl_rcopyto!(first(pairs), idx)
    knl_rcopyto!(Base.tail(pairs), idx)
end
Base.@propagate_inbounds knl_rcopyto!(pairs::Tuple{T}, idx) where T =
    knl_rcopyto!(first(pairs), idx)
@inline knl_rcopyto!(pairs::Tuple{}, idx) = nothing

function get_array(AType, s)
    return AType(zeros(s...))
end

function get_arrays(sym, s, AType, n=10)
    fn = ntuple(i->Symbol(sym, i), n)
    return (;zip(fn,ntuple(_->get_array(AType, s), n))...)
end

import CUDA
import Adapt
function copyto_cuda!(pairs::Tuple) # (Pair(dest1, bc1),Pair(dest2, bc2),...)
    nitems = length(parent(first(pairs).first))
    max_threads = 256 # can be higher if conditions permit
    nthreads = min(max_threads, nitems)
    nblocks = cld(nitems, nthreads)
    CUDA.@cuda threads = (nthreads) blocks = (nblocks) knl_multi_copyto!(pairs)
    return nothing
end
function knl_multi_copyto!(pairs::NTuple{N,T}) where {N, T<: Pair}
    nitems = length(first(pairs).first)
    gidx = CUDA.threadIdx().x + (CUDA.blockIdx().x - 1) * CUDA.blockDim().x
    if gidx < nitems
        idx = gidx
        knl_rcopyto!(pairs, gidx)
    end
    return nothing
end

function perf_kernel_hard_coded!(X, Y, ::GPU)
    x1 = X.x1
    nitems = length(parent(x1))
    max_threads = 256 # can be higher if conditions permit
    nthreads = min(max_threads, nitems)
    nblocks = cld(nitems, nthreads)
    CUDA.@cuda threads = (nthreads) blocks = (nblocks) knl_multi_copyto_hard_coded!(X, Y, Val(nitems))
end
function knl_multi_copyto_hard_coded!(X, Y, ::Val{nitems}) where {nitems}
    (;x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) = X
    (;y1,y2,y3,y4,y5,y6,y7,y8,y9,y10) = Y
    gidx = CUDA.threadIdx().x + (CUDA.blockIdx().x - 1) * CUDA.blockDim().x
    if gidx < nitems
        idx = gidx
        y1[idx] = x1[idx]+x2[idx]+x3[idx]+x4[idx]
        y2[idx] = x2[idx]+x3[idx]+x4[idx]+x5[idx]
        y3[idx] = x3[idx]+x4[idx]+x5[idx]+x6[idx]
        y4[idx] = x4[idx]+x5[idx]+x6[idx]+x7[idx]
        y5[idx] = x5[idx]+x6[idx]+x7[idx]+x8[idx]
        y6[idx] = x6[idx]+x7[idx]+x8[idx]+x9[idx]
        y7[idx] = x7[idx]+x8[idx]+x9[idx]+x10[idx]
    end
    return nothing
end

function adapt_pairs(pairs, ::GPU)
    to = CUDA.KernelAdaptor()
    return map(pairs) do p
        Pair(Adapt.adapt(to, p.first), Adapt.adapt(to, p.second))
    end
end
benchmark_kernel!(f!, X, Y, ::GPU) = CUDA.@sync BenchmarkTools.@benchmark $f!($X, $Y);

has_cuda = CUDA.has_cuda()
AType = has_cuda ? CUDA.CuArray : Array
@show AType
s = (50,5,5,6,50)
X = get_arrays(:x, s, AType)
Y = get_arrays(:y, s, AType)

adapt_pairs(pairs, ::CPU) = pairs

adapt_pairs(pairs) = adapt_pairs(pairs, device(first(pairs).first))

function perf_kernel_now!(X, Y)
    (;x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) = X
    (;y1,y2,y3,y4,y5,y6,y7,y8,y9,y10) = Y
    # 7 writes; 10 unique reads
    # 7 writes; 28 reads including redundant ones
    @. y1 = x1+x2+x3+x4
    @. y2 = x2+x3+x4+x5
    @. y3 = x3+x4+x5+x6
    @. y4 = x4+x5+x6+x7
    @. y5 = x5+x6+x7+x8
    @. y6 = x6+x7+x8+x9
    @. y7 = x7+x8+x9+x10
    return nothing
end
perf_kernel_custom!(X, Y) = perf_kernel_custom!(X, Y, device(X.x1))

function perf_kernel_custom!(X, Y, ::GPU)
    (;x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) = X;
    (;y1,y2,y3,y4,y5,y6,y7,y8,y9,y10) = Y;
    pairs = (
        Pair(y1, Base.Broadcast.instantiate(Base.broadcasted(+, x1, x2, x3, x4))),
        Pair(y2, Base.Broadcast.instantiate(Base.broadcasted(+, x2, x3, x4, x5))),
        Pair(y3, Base.Broadcast.instantiate(Base.broadcasted(+, x3, x4, x5, x6))),
        Pair(y4, Base.Broadcast.instantiate(Base.broadcasted(+, x4, x5, x6, x7))),
        Pair(y5, Base.Broadcast.instantiate(Base.broadcasted(+, x5, x6, x7, x8))),
        Pair(y6, Base.Broadcast.instantiate(Base.broadcasted(+, x6, x7, x8, x9))),
        Pair(y7, Base.Broadcast.instantiate(Base.broadcasted(+, x7, x8, x9, x10))),
    );
    new_pairs = adapt_pairs(pairs)
    copyto_cuda!(new_pairs)
end

function perf_kernel_custom!(X, Y, ::CPU)
    (;x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) = X;
    (;y1,y2,y3,y4,y5,y6,y7,y8,y9,y10) = Y;
    pairs = (
        Pair(y1, Base.Broadcast.instantiate(Base.broadcasted(+, x1, x2, x3, x4))),
        Pair(y2, Base.Broadcast.instantiate(Base.broadcasted(+, x2, x3, x4, x5))),
        Pair(y3, Base.Broadcast.instantiate(Base.broadcasted(+, x3, x4, x5, x6))),
        Pair(y4, Base.Broadcast.instantiate(Base.broadcasted(+, x4, x5, x6, x7))),
        Pair(y5, Base.Broadcast.instantiate(Base.broadcasted(+, x5, x6, x7, x8))),
        Pair(y6, Base.Broadcast.instantiate(Base.broadcasted(+, x6, x7, x8, x9))),
        Pair(y7, Base.Broadcast.instantiate(Base.broadcasted(+, x7, x8, x9, x10))),
    );
    new_pairs = adapt_pairs(pairs)
    copyto_cpu!(pairs)
end

perf_kernel_hard_coded!(X, Y) = perf_kernel_hard_coded!(X, Y, device(X.x1))

function perf_kernel_hard_coded!(X, Y, ::CPU)
    (;x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) = X
    (;y1,y2,y3,y4,y5,y6,y7,y8,y9,y10) = Y
    @inbounds for i in eachindex(x1)
        y1[i] = x1[i]+x2[i]+x3[i]+x4[i]
        y2[i] = x2[i]+x3[i]+x4[i]+x5[i]
        y3[i] = x3[i]+x4[i]+x5[i]+x6[i]
        y4[i] = x4[i]+x5[i]+x6[i]+x7[i]
        y5[i] = x5[i]+x6[i]+x7[i]+x8[i]
        y6[i] = x6[i]+x7[i]+x8[i]+x9[i]
        y7[i] = x7[i]+x8[i]+x9[i]+x10[i]
    end
end

function benchmark_kernel!(f!, X, Y)
    println("\n--------------------------- $(nameof(typeof(f!))) ")
    trial = benchmark_kernel!(f!, X, Y, device(X.x1))
    show(stdout, MIME("text/plain"), trial);
end

benchmark_kernel!(f!, X, Y, ::CPU) = BenchmarkTools.@benchmark $f!($X, $Y);

# Compile
perf_kernel_now!(X, Y)
perf_kernel_custom!(X, Y)
perf_kernel_hard_coded!(X, Y)

# Benchmark
benchmark_kernel!(perf_kernel_now!, X, Y)
benchmark_kernel!(perf_kernel_custom!, X, Y)
benchmark_kernel!(perf_kernel_hard_coded!, X, Y)

# function perf_kernel_syntax!(X, Y)
#     (;x1,x2,x3,x4,x5,x6,x7,x8,x9,x10) = X
#     (;y1,y2,y3,y4,y5,y6,y7,y8,y9,y10) = Y
#     @fused begin
#         @. y1 = x1+x2+x3+x4
#         @. y2 = x2+x3+x4+x5
#         @. y3 = x3+x4+x5+x6
#         @. y4 = x4+x5+x6+x7
#         @. y5 = x5+x6+x7+x8
#         @. y6 = x6+x7+x8+x9
#         @. y7 = x7+x8+x9+x10
#     end
# end

nothing
```

**Comment by charleskawczynski** [comment]
On my mac, I get
```julia
AType = Array

--------------------------- #perf_kernel_now! 
BenchmarkTools.Trial: 1726 samples with 1 evaluation.
 Range (min … max):  2.449 ms …   9.992 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     2.534 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   2.887 ms ± 908.383 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █▆▄▃▂▁▁▁▁                                                    
  █████████████▇▇▇▆▅▇▅▆▅▆▅▆▆▆▅▇▆▅▅▅▆▅▅▅▆▄▄▁▄▅▅▄▅▆▅▅▁▅▁▃▃▃▃▄▃▃ █
  2.45 ms      Histogram: log(frequency) by time         7 ms <

 Memory estimate: 0 bytes, allocs estimate: 0.
--------------------------- #perf_kernel_custom! 
BenchmarkTools.Trial: 298 samples with 1 evaluation.
 Range (min … max):  16.291 ms …  21.178 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     16.663 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   16.772 ms ± 441.925 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

             ▅█                                                 
  ▃▃▃▃▁▃▂▃▃▃▄██▄▄▂▃▃▂▃▃▃▃▄▃▃▁▃▂▂▃▂▂▃▂▁▂▁▁▁▁▂▁▁▁▂▁▂▁▁▁▂▁▁▁▁▁▂▁▂ ▂
  16.3 ms         Histogram: frequency by time         18.1 ms <

 Memory estimate: 0 bytes, allocs estimate: 0.
--------------------------- #perf_kernel_hard_coded! 
BenchmarkTools.Trial: 2842 samples with 1 evaluation.
 Range (min … max):  1.318 ms …   5.151 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.585 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.746 ms ± 481.763 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

   █▁                                                          
  ▄██▆▅▅▄▄▅▄▄▄▃▃▃▃▃▃▃▃▃▃▃▃▃▂▃▂▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▁▂▂▂▂▂▂▂ ▃
  1.32 ms         Histogram: frequency by time         3.5 ms <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

**Comment by charleskawczynski** [comment]
I'm pleasantly surprised that the generic/recursive pattern appears (somehow) more performant than the hard-coded one, but I'll take it!

**Comment by tapios** [comment]
Really nice and helpful. Thank you!

**Comment by charleskawczynski** [comment]
Regarding the main performance issue: too many loads/stores due to too many kernel launches:

 - [x] We developed [MultiBroadcastFusion.jl](https://github.com/CliMA/MultiBroadcastFusion.jl), which supports collecting multiple broadcast expressions into a tuple.
 - [ ] Began supporting MultiBroadcastFusion kernels https://github.com/CliMA/ClimaCore.jl/pull/1641. There's different things we can do:
   - [ ] Support fused kernels, where the compiler can hoist reads / writes
   - [ ] Support parallel kernes (thread per broadcast expression), where more gpu resources can result in faster fused kernels
   - [ ] Benchmark kernels to see when we want to use each approach. We may even be able to develop heuristics to decide/dispatch to a target implementation.
 - [ ] This is a fair bit of work, and right now we're only starting with similar space pointwise kernels, but we can support quite a few. All of these decisions are made in ClimaCore (MultiBroadcastFusion.jl is very close to being feature complete):
   - [ ] Similar space pointwise operations
   - [ ] Similar space FD operations
   - [ ] Similar space SE operations
   - [ ] Similar Pointwise and FD operations (eliminates boundaries for pointwise and FD operations)
   - [ ] Similar Pointwise and SE operations (eliminates boundaries for pointwise and SE operations)
   - [ ] Dissimilar space operations. Pointwise first, then, combinations? This could get unwieldy fast, so we should think about which ones we want to implement.
   - [ ] There are probably more, but these seem to be conceptually the simplest to implement, and we can probably do quite a bit of fusion just with these alone.
