### ISSUE TITLE
O1.2.6 (atmos) 1 SYPD for AMIP on a single A100

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2943]
# The Climate Modeling Alliance
### Purpose

To be filled...

### Task Breakdown And Schedule

```[tasklist]
### Scope of Work
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/635
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2632
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/700
- [ ] https://github.com/CliMA/ClimaCoupler.jl/issues/767
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1995
```

### SDI Revision Log

[240429] @cmbengue added a placeholder tasklist

**Comment by LenkaNovak** [comment]
@szy21 , do you mind if me move this to 1.2.6, since we already achieve 1.2.5 for AMIP? E.g. [here](https://buildkite.com/clima/climacoupler-longruns/builds/668#018f325b-a6d2-4c2d-b67f-1416484fda11)

**Comment by szy21** [comment]
> @szy21 , do you mind if me move this to 1.2.6, since we already achieve 1.2.5 for AMIP? E.g. [here](https://buildkite.com/clima/climacoupler-longruns/builds/668#018f325b-a6d2-4c2d-b67f-1416484fda11)

Sure, that sounds good. Thanks!

**Comment by LenkaNovak** [comment]
Awesome, thanks! Cc'ing @juliasloan25

**Comment by szy21** [comment]
We should open a new issue on performance with updated information. Closing this now.
