### ISSUE TITLE
Improve prognostic implicit edmf performance

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#2950]
This issue is for tracking the performance of the prognostic implicit edmf performance.
```[tasklist]
### Tasks
- [ ] Make a reproducer for the kernels discussed here: https://github.com/CliMA/ClimaAtmos.jl/pull/2951#issuecomment-2077315044
- [ ] Implement shared memory for FD kernels, see if this
- [ ] Collect launch statistics/benchmarks based on hard-coded threads/blocks vs `CUDA.launch_configuration`
- [ ] Implement and apply broadcast fusion for similar pointwise expressions
- [ ] Implement and apply broadcast fusion for similar FD expressions
```

**Comment by charleskawczynski** [comment]
I looked at the nvtx report from #2947, and this is what I'm seeing:

Here is a full `step!` (labeled by `ClimaTimeSteppers` on the left), for the big picture view:

<img width="1961" alt="Screen Shot 2024-04-24 at 9 25 40 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/1880641/4be757bf-3106-485d-a058-a906775008fb">

The 3 "large" cpu calls to `remaining_tendency!` / `hyperdiffusion_tendency!` are the ones that follow the implicit solve. They only appear large because _many_ kernels are launched during the implicit solve, which pile up in the gpu queue, and there's a `CUDA.synchronize` call in `hyperdiffusion_tendency!`'s DSS call.

Let's zoom in to see who is responsible for these kernel launches. I'll click on the cpu functions (labeled `ClimaAtmos`), and the kernels (`99.9% Kernels (named by NVTX)` above will highlight:

`dss!`:

<img width="1972" alt="Screen Shot 2024-04-24 at 9 40 36 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/1880641/ef751f09-a6b0-40b5-9f1b-fea3e107b6f9">

`set_precomputed_quantities!`

<img width="1969" alt="Screen Shot 2024-04-24 at 9 43 46 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/1880641/e7584ebd-9c20-47bb-8048-adb62bceb738">

`wfact!`:

<img width="1977" alt="Screen Shot 2024-04-24 at 9 44 15 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/1880641/3b711d1e-7e76-433f-bc0a-d98a1f6a58b9">

`implicit_tendency!`:

<img width="1976" alt="Screen Shot 2024-04-24 at 9 44 46 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/1880641/bdbcfd24-fa27-4a2e-ac64-1464bd9b8076">

`ldiv!`:

<img width="1976" alt="Screen Shot 2024-04-24 at 9 45 08 AM" src="https://github.com/CliMA/ClimaAtmos.jl/assets/1880641/1035d5ab-ad82-41e8-b1c8-2b3b29489a6b">

The one after that is another call to `set_precomputed_quantities!`.

### Summary

Some things are obvious and clear (for a single A100 gpu):
 - Most of the gpu time is spent in `ldiv!`.
 - Next comes `set_precomputed_quantities!`, not far behind is `wfact!`, then `implicit_tendency!`, then `dss!`
 - The _single_ most expensive _kernel_ is the call to `buoyancy_gradients` (in `set_precomputed_quantities!`), which takes about 8 ms

Perhaps fortunately, `ldiv!` basically calls `MatrixFields.field_matrix_solve!(A.solver, x, A.matrix, b)`, so the majority of the performance improvements can be done in ClimaCore, hopefully without even requiring changes in ClimaAtmos.

**Comment by charleskawczynski** [comment]
### Summary

Recap of total duration of gpu launched kernels:
 - `dss!` (2.7 ms)
 - `set_precomputed_quantities!` (22.7 ms)
 - `wfact!` (18.2 ms)
 - `implicit_tendency!` (7.4 ms)
 - `ldiv!` (107.4 ms)

Some things are obvious and clear (for a single A100 gpu):
 - Most of the gpu time is spent in `ldiv!`.
 - Next comes `set_precomputed_quantities!`, not far behind is `wfact!`, then `implicit_tendency!`, then `dss!`
 - The _single_ most expensive _kernel_ is the call to `buoyancy_gradients` (in `set_precomputed_quantities!`), which takes about 8 ms

Perhaps fortunately, `ldiv!` basically calls `MatrixFields.field_matrix_solve!(A.solver, x, A.matrix, b)`, so the majority of the performance improvements can be done in ClimaCore, hopefully without even requiring changes in ClimaAtmos.

**Comment by charleskawczynski** [comment]
Odd, I didn't highlight the kernels for `remaining_tendency!`. I wonder what they looked like. I don't think I have this nsight report anymore..
