### ISSUE TITLE
O1.5.3d Run AMIP with prognostic EDMF and simple land model

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#2953]
# The Climate Modeling Alliance
### Purpose

Demonstrate stable aquaplanet simulation with prognostic EDMF
### People and Personnel

- Lead: @szy21 
- Collaborators: @dennisYatunin  

### CC

```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2974
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2904
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/2976
```
