### ISSUE TITLE
Integration testing-focused AMIP roadmap

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#301]
The purpose of this issue is to outline an integration testing-focused roadmap, in order to accelerate iteration and optimally parallelize work across team members. Several tasks are needed to do this, below is an attempt to enumerate / outline these items

### Integration-testing-focused tasks

 - [x] `#1` From the AMIP roadmap document, extract a finite number of CI jobs (let's call them "milestones" with a unique JobID) which satisfy the following:
     - Using a list of composable acronyms for physics and configurations (a draft is below)
     - Write down a job unique JobID, to run on CI, for each item
 - [x] `#2` Sketch a dependency graph to help identify bottle necks and help with load balancing of distributed work -> Moved to [CA#374](https://github.com/CliMA/ClimaAtmos.jl/pull/374).
 - [x] `#3` Derive appropriate names for each job (i.e., a JobID). Depends on `#1`
 - [x] `#4` Add regression testing infrastructure. [CA#312](https://github.com/CliMA/ClimaAtmos.jl/pull/312), [CA#321](https://github.com/CliMA/ClimaAtmos.jl/pull/321), [CA#325](https://github.com/CliMA/ClimaAtmos.jl/pull/325)
 - [x] `#5` Add buildkite jobs for both regression tests and long runs. Loosely depends on `#1`, `#3`, tied to and `#4`. [CA#312](https://github.com/CliMA/ClimaAtmos.jl/pull/312), [CA#321](https://github.com/CliMA/ClimaAtmos.jl/pull/321), [CA#325](https://github.com/CliMA/ClimaAtmos.jl/pull/325)
 - [x] `#6` Add buildkite jobs for long runs [CA#298](https://github.com/CliMA/ClimaAtmos.jl/pull/298), [CA#304](https://github.com/CliMA/ClimaAtmos.jl/pull/304), [CA#317](https://github.com/CliMA/ClimaAtmos.jl/pull/317), [CA#319](https://github.com/CliMA/ClimaAtmos.jl/pull/319), [CA#323](https://github.com/CliMA/ClimaAtmos.jl/pull/323)
 - [ ] `#7` Add command-line options for each job so that team members have necessary flags to turn on/off physics for each job-- this will allow team members can more easily work on a unified code rather than developing separate scripts. Somewhat depends on `#1` and `#3` [CA#294](https://github.com/CliMA/ClimaAtmos.jl/pull/294), [CA#317](https://github.com/CliMA/ClimaAtmos.jl/pull/317), [CA#303](https://github.com/CliMA/ClimaAtmos.jl/pull/303), [CA#322](https://github.com/CliMA/ClimaAtmos.jl/pull/322)
 - [x] `#8` Add single-node performance monitoring [CA#318](https://github.com/CliMA/ClimaAtmos.jl/pull/318)
 - [x] `#9` Solidify job names with appropriate flags. Depends on `#1`, `#3` and [CA#7](https://github.com/CliMA/ClimaAtmos.jl/pull/318). [CA#322](https://github.com/CliMA/ClimaAtmos.jl/pull/322)

### Physics acronyms
 - DY = Dynamical core equations
 - T = Topography
 - GW = Gravity wave
 - TC = TurbulenceConvection
 - R = Radiation (i.e., RRTMGP.jl)
 - 0M = 0-moment microphysics
 - VD = Vertical diffusion
 - HS = Held Suarez forcing
 - L = Land
 - M = moisture (dry, equil, non-equil)

### Configuration acronyms
 - SP = Spherical configuration - A full 3D spherical configuration, at coarse or fine resolution (determined by cli arguments)
 - SC = Single Column configuraiton - A "single column" configuration where we run a spherical case with 6 faces, 1 element per face, 0-poly order and horizontally decoupled. These configurations with horizontal coupling (i.e., horizontal advection) + higher resolution should yield an effectively 3D spherical case

### Notes
   - The CI jobs will run with two durations: one in ~20 min for regression tests (triggered per pushed commit in `.buildkite/pipeline.yml`) and long runs for validating against published references (triggered daily `.buildkite/longruns/pipeline.yml`).

---

I'm currently working towards `#4`, while also working with @bischtob on `#1` and `#2` (@szy21, can you also help with this?). I've also spoken with @dennisYatunin about `#6`, and we're on the same page.

Once items 1-7 are complete (IMO, this is in some sense a bottle neck), everyone working on integrating components will have running examples to iterate on, and sufficient command line flags to turn on/off whatever pieces they need for any of the milestones. Any behavioral changes will be tracked via regression tests, and visual output will be tracked daily. I'm hoping items 1-7 can be finished in ~ 1 week at most

 - @yairchn with TurbulenceConvection
 - @dennisYatunin with Radiation
 - @akshaysridhar with Topography
 - @Zhengyu-Huang & @yairchn with implicit solver for TurbulenceConvection
 - @Sriharsha with Distributed work
 - @jiahe23 @simonbyrne, @charleskawczynski (and others) with automating end-to-end visualization
 - @simonbyrne and @valeriabarra with custom time steppers + limiters
 - @simonbyrne, @sriharshakandala, and @charleskawczynski on time-to-solution performance
 - Collaborative effort on documentation

---

I'm sure I've missed some things but I'll update this list as time goes on.

**Comment by szy21** [comment]
Yes, I can help with `#1` and `#2`. Would you like me to write down a list here?

**Comment by charleskawczynski** [comment]
That would be great, thank you!

**Comment by sriharshakandala** [comment]
Hello Charlie,

I am happy to help with distribution, time-to-solution performance and some other items as well. May be, we can have a quick meeting tomorrow?

From: Charles Kawczynski ***@***.***>
Date: Thursday, April 14, 2022 at 2:45 PM
To: CliMA/ClimaAtmos.jl ***@***.***>
Cc: Kandala, Sriharsha ***@***.***>, Mention ***@***.***>
Subject: Re: [CliMA/ClimaAtmos.jl] Integration testing-focused AMIP roadmap (Issue #301)

That would be great, thank you!

**Comment by szy21** [comment]
SP (Spherical configuration):
dry_baroclinic_wave: dry BW
dry_held_suarez: dry HS
dry_held_suarez_topo: dry HS + T
moist_baroclinic_wave: BW + 0M
moist_held_suarez: HS + SF + VD + 0M
moist_idealized_aqua_grayrad: HS + SF + VD + 0M + R (gray)
moist_idealized_aqua_allskyrad: HS + SF + VD + 0M + R (all-sky)
moist_idealized_aqua_allskyrad_topo: HS + SF + VD + 0M + R (all_sky) + T
moist_idealized_aqua_allskyrad_edmf: HS + SF + R (all-sky) + TC
moist_idealized_aqua_allskyrad_edmf_topo: HS + SF + R (all-sky) + TC + T

SC (Single Column configuration):
radiative_equilibrium_gray: R (gray)
radiative_equilibrium_allsky: R (all-sky)
radiative_convective_equilibrium: R (all-sky) + TC

I'm sure some of these might not be accurate but I will update it if anything comes to my mind. I stopped at the moist_idealized_aqua_allskyrad_edmf_topo because after that we need land and coupler, and I don't know enough about that. I'm not good at coming up with names either, and I'm sure they could have better names!

**Comment by charleskawczynski** [comment]
I've added `moist` physics (which can take on `dry`, `equil`, and `non-equil`). @szy21, I've edited your comment by removing the prepending `moist_` and adding ` + equil`, please fix if this is the case (if any need to be `non-equil`).

@dennisYatunin, this is one of the places where we can migrate from `_moist` scripts to dispatching on a moisture model type.

**Comment by szy21** [comment]
Thanks @charleskawczynski. Yes, we can do everything with `equil`. One thing that keeps bothering me is that it's not accurate to call `BW` and `HS` configurations because they are essentially the same dycore equations, just `HS` has an extra forcing term. Also everything starting with idealized_aqua is not `HS`, I just used it because it may be easier to understand. Do you want me to change it to make it more accurate?

**Comment by charleskawczynski** [comment]
Yes, that would be great, thanks!

**Comment by charleskawczynski** [comment]
I addressed at least part of `#9` in #318.

**Comment by charleskawczynski** [comment]
Translating [this](https://github.com/CliMA/ClimaAtmos.jl/issues/301#issuecomment-1099699902) into how I see this working, the `job_id: flags` will look something like (I've made another minor tweak):

```
baroclinic_wave: --config SP
held_suarez: --HS true --config SP
held_suarez_topo: --HS true --topo true --config SP
equil_baroclinic_wave: --moist equil --micro 0M --config SP
equil_held_suarez: --moist equil --HS true --SF true --VD true --micro 0M --config SP
equil_idealized_aqua_grayrad: --moist equil --SF true --VD true --micro 0M --rad gray --config SP
equil_idealized_aqua_allskyrad: --moist equil --SF true --VD true --micro 0M --rad AllSky --config SP
equil_idealized_aqua_allskyrad_topo: --moist equil --SF true --VD true --micro 0M --rad AllSky --topo true --config SP
equil_idealized_aqua_allskyrad_edmf: --moist equil --SF true --rad AllSky --TC true --config SP
equil_idealized_aqua_allskyrad_edmf_topo: --moist equil --SF true --rad AllSky --TC true --topo true --config SP
radiative_equilibrium_gray: --DY false --rad gray --config SC
radiative_equilibrium_allsky: --DY false --rad AllSky --config SC
radiative_convective_equilibrium: --DY false --rad AllSky --TC true --config SC
```
Which means we need to add the following cli options (with maybe better names):

```
--config [SP, SC] (no default)
--HS [false (default), true]
--topo [false (default), true]
--moist [dry (default), equil, non_equil]
--micro [nothing (default), 0M, 1M]
--SF [false (default), true]
--VD [false (default), true]
--rad [nothing (default), gray, clear_sky, all_sky]
--TC [false (default), true]
--DY [true (default), false]
```

**Comment by szy21** [comment]
Looks good to me in general. One thing I am not sure about is that for the single column configuration, do we want to use what you suggest (a spherical case with 6 faces, 1 element per face, 0-poly order and horizontally decoupled), or do we want to use a 2D hybrid plane case with 1 element and 0 poly order? Maybe they are essentially the same?

**Comment by charleskawczynski** [comment]
> Looks good to me in general. 

Oops, forgot to hit Comment. They're essentially the same, so it's not a big difference / issue.
