### ISSUE TITLE
Run `ClimaAtmos` on `Google Cloud`

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaAtmos.jl#3026]
# The Climate Modeling Alliance
### Purpose
Setup an automated build system to deploy `ClimaAtmos.jl` on the google cloud. 

### Cost/Benefits/Risks
Benefits:
- The approach can be generalized to other cloud services and supercomputers.
- Provides access to nodes having up to (16) GPUs for benchmarking scaling performance.

### People and Personnel
- Lead: @sriharshakandala , @charleskawczynski 
- Collaborators:
- Reviewers: -->

### Components
- Setup an automated build system for running ClimaAtmos on Google Cloud
- Benchmark scaling performance on up to (16) GPUs on a single node
### CC
@tapios @simonbyrne @cmbengue

### Tasks
- [x] Install/configure and run `ClimaAtmos.jl` on a single GPU on GCP
- [x] Install/configure SLURM for single node and multi-node GCP configurations
- [x] Setup environment for CliMA software stack
- [ ] Compile strong scaling data on H100 GPUs
- [ ] Add curated documentation to ClimaDocs

**Comment by Sbozzolo** [comment]
Would it be possible to have more details on this SDI?

I am interested in potential sinergies to improve the resiliance of our CI infrastructure

**Comment by Sbozzolo** [comment]
Leaving this question for when time comes:

How are you planning on handling larger input files (as the ones in ClimaArtifacts)?
