### ISSUE TITLE
Add aerosol radiative effects

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaAtmos.jl#3140]
```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/3147
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3154
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3170
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/3184
```

**Comment by szy21** [comment]
Change in clear-sky net TOA SW due to SO4 in aquaplanet:
![image](https://github.com/CliMA/ClimaAtmos.jl/assets/11598433/8bf359cc-0e3a-4d63-a172-245e55532899)

**Comment by Sbozzolo** [comment]
Is this using the concentrations read from file?

**Comment by szy21** [comment]
> Is this using the concentrations read from file?

Yes, it uses the aerosol concentration in the tracer cache [here](https://github.com/CliMA/ClimaAtmos.jl/blob/a788613da31903df3556419bcc989ac841ae382f/src/callbacks/callbacks.jl#L166). You can see it is only SO4 now. I will extend it to other types of aerosols.

**Comment by Sbozzolo** [comment]
Awesome, just making sure :)

**Comment by szy21** [comment]
Change in clear-sky net TOA SW due to all aerosols in aquaplanet:
![image](https://github.com/CliMA/ClimaAtmos.jl/assets/11598433/10546071-24fb-4916-bf85-3ce5fc4cfce5)

I think it looks reasonable. The two things missing are:
-  #3185, which we can address later
- correct interpolation of aerosol time series, which will be addressed in ClimaUtilities.

**Comment by szy21** [comment]
I'm closing this now. The remaining interpolation issue has been added to https://github.com/CliMA/ClimaAtmos.jl/issues/3197
