### ISSUE TITLE
Prescribed ozone concentration

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaAtmos.jl#3198]
Minimal requirement is using zonally averaged seasonal-mean ozone distributions, as a function of height after data of Hering and Borden (1965) 

```[tasklist]
### Tasks
- [x] https://github.com/CliMA/ClimaArtifacts/pull/30
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/3241
- [x] Use prescribed ozone in the amip run
```

**Comment by szy21** [comment]
The AMIP simulation is now run with prescribed ozone.
