### ISSUE TITLE
Implicit solver for the EDMF 

### ISSUE THREAD

**Issue by yairchn** [CliMA/ClimaAtmos.jl#789]
## Purpose
The goal is to run the EDMF with a timestep of ~100sec and make sure the RHS evaluation is not significantly changed. This would allow us to use EDMF in a global model.

**Jan 18th update:** The implicit EDMF simulations we have tried running were unstable. We decided to refactor the EDMF filters to improve stability before debugging the implicit implementation further. See #1104 for updates.

## People and Personnel
- Lead: @trontrytel 
- Collaborators: @dennisYatunin , @dennisYatunin , @trontrytel, @Zhengyu-Huang
- Reviewers: @charleskawczynski,  @trontrytel, @haakon-e 

## Inputs
The equations relating to this code change will be added to the following document:
https://www.overleaf.com/6233444242pddjjhxqjpyw

## Results and deliverables
- [ ] Plots showing last hour mean profiles of Bomex with explicit (dt~1sec) and implicit (dt = 100sec) EDMF. 
- [ ] Similar plots for other compressible single column cases: DYCOMS RF01, TRMM (with 0 moment microphysics).
 
## Task Breakdown And Tentative Due Date
(A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results)
- [x] Use `Covariant3Vector` for vertical velocity type (@trontrytel , @simonbyrne ) https://github.com/CliMA/ClimaAtmos.jl/pull/992 ~~Oct 19th~~, Oct 26
- [x] Fix https://github.com/CliMA/ClimaAtmos.jl/issues/1017 Oct 25
- [x] Add JFNK test to the CI pipeline: https://github.com/CliMA/ClimaAtmos.jl/pull/1080
- [x] Cleanup the way filtering is done for edmf: https://github.com/CliMA/ClimaAtmos.jl/pull/1092. Nov 9th
- [x] Solve the EDMF advection + diffusion implicitly using JFNK methods https://github.com/CliMA/ClimaAtmos.jl/pull/1021  (@dennisYatunin, @trontrytel ) ~~Oct 19th~~, ~~Oct 28~~, Nov 14th.
- [x] Create a sandbox for testing different Jacobians for edmf. We need a way to specify Jacobian blocks and a simple method to use them (preconditioner for JFNK) https://github.com/CliMA/ClimaAtmos.jl/pull/1130 (@dennisYatunin ) Nov 19th
- [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1155, https://github.com/CliMA/ClimaTimeSteppers.jl/pull/86
- [x] ~~https://github.com/CliMA/ClimaAtmos.jl/issues/1157~~
- [x] #1173
- [ ] https://github.com/CliMA/ClimaAtmos.jl/pull/1148 Nov 28th
- [ ] https://github.com/CliMA/ClimaAtmos.jl/issues/1156
- [ ] Equations writeup
- [x] #1180
- [ ] Run (Soares, Bomex, Dycoms, TRMM) CI test cases with the chosen implicit setup (@trontrytel ) ~~Nov 3~~, ~~Nov 28~~

## Proposed Delivery Date
~~Nov 1st~~, ~~Nov 3th~~  ~~Nov 28th~~

**Comment by charleskawczynski** [comment]
Can we expand the task breakdown and update the tentative due date?

**Comment by charleskawczynski** [comment]
### EDMF-dycore field unification

    - [x] thermo state #867
    - [ ] pressure #875
    - [ ] `ᶜT` No PR yet
    - [ ] `ᶜω³` No PR yet
    - [ ] `ᶜK` No PR yet
    - [ ] `ᶜuvw` No PR yet
    - [ ] `Yₜ`? No PR yet
    - [ ] `ᶠω¹²` No PR yet
    - [ ] `ᶠu¹²` No PR yet
    - [ ] `ᶠu³` No PR yet
    - [ ] `ᶜf` No PR yet
    - [ ] `T_sfc` (would it be easier to change this to `ᶠts_sfc`?) No PR yet

### EDMF-dycore type unification
 - [ ] `EquilibriumMoisture` and `EquilMoistModel`
 - [ ] `NonEquilibriumMoisture` and `NonEquilMoistModel`
This code will need to be added into `src/`, so that edmf and the driver is able to access them from a common scope

**Comment by trontrytel** [comment]
Closing this one for now. It is not done, but noone is working on it right now. All the effort is focused on:
- explicit and diagnostic EDMFX
- making additional changes in ClimaCore to support implicit solver.
