### ISSUE TITLE
Explicit EDMF on a sphere

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#949]
## Purpose
The goal is to add a spherical baroclinic wave test case using rhoe, equilibrium moisture, 0-moment microphysics and edmf turbulence closure. The simulation should be added to the CI and should be able to run for ~20minutes total CI time. 

## Cost/Benefits/Risks
This is essential for the final model. We could also expand on this setup and later have CI cases in a multi-column box configuration for testing edmf advection terms and topography.

## People and Personnel
- Lead: @trontrytel, @dennisYatunin  
- Collaborators: @haakon-e  
- Reviewers: @tapios , @charleskawczynski, @szy21 

## Results and deliverables
 - [x] A buildkite job with edmf on a sphere running for 20 minutes computational time.
 - [x] Add edmf to the perf target (flame graph).

## Task Breakdown And Tentative Due Date
 - [x] Fix AxisTensor (metric terms) conversions (#947)
 - [x] Refactor case-specific radiation for SCM vs GCM runs (@charleskawczynski , @trontrytel) #960 #959, https://github.com/CliMA/ClimaAtmos.jl/pull/974, https://github.com/CliMA/ClimaAtmos.jl/pull/960, https://github.com/CliMA/ClimaAtmos.jl/pull/971, https://github.com/CliMA/ClimaAtmos.jl/pull/968, https://github.com/CliMA/ClimaAtmos.jl/pull/966, https://github.com/CliMA/ClimaAtmos.jl/pull/964, https://github.com/CliMA/ClimaAtmos.jl/pull/959
 - [x] Unify thermo state (@charleskawczynski )
 - [x] Refactor case-specific subsidence and LS advection for SCM vs GCM runs, (@charleskawczynski , @trontrytel) #1022, #1018
 - [x] Refactor case-specific surface BC  for SCm vs GCM runs https://github.com/CliMA/ClimaAtmos.jl/pull/1147 (@charleskawczynski , @trontrytel)
 - [x] Refactor precipitation treatment between the TC and CA, https://github.com/CliMA/ClimaAtmos.jl/pull/1149,  https://github.com/CliMA/ClimaAtmos.jl/pull/1167, https://github.com/CliMA/ClimaAtmos.jl/pull/1108 (@trontrytel , @charleskawczynski)
 - [x] Add a buildkite job with edmf on a sphere https://github.com/CliMA/ClimaAtmos.jl/pull/916 ~~Oct 28~~
 - [x] #1345
 - [x] #1357
 - [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1390
 - [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1388
 - [x] #1295
 - [x] https://github.com/CliMA/ClimaAtmos.jl/issues/1393
 - [x] #1296
 - [x] Add a buildkite job with edmf on a sphere with correct initial and boundary conditions. Update the performnce monitoring job.
 - [x] Address performance issues (if any  arise)

## Proposed Delivery Date
~~(Hopefully) Wenesday, November 1~~
~~March 1st~~

## CC
@tapios @simonbyrne @cmbengue

**Comment by trontrytel** [comment]
CI case we are aiming for:

`julia --color=yes --project=examples examples/hybrid/driver.jl
--vert_diff true 
--surface_scheme monin_obukhov
--moist equil
--rad gray 
--microphy 0M 
--turbconv edmf 
--job_id sphere_aquaplanet_rhoe_equilmoist_gray_edmf 
--skip_tc_hydro_balance true 
--dt 1secs 
--t_end 6hours`

Long runs CI cases we are aiming for (low-res and high-res):

`julia --color=yes --project=examples examples/hybrid/driver.jl 
--threads=8 
--vert_diff true
--surface_scheme monin_obukhov
--moist equil
--rad gray
--microphy 0M
--turbconv edmf
--job_id longrun_sphere_aquaplanet_rhoe_equilmoist_gray_edmf_lowres
--skip_tc_hydro_balance true
--dt 1secs
--t_end 2days`

`julia --project=examples examples/hybrid/driver.jl
 --threads 8
--vert_diff true
--surface_scheme monin_obukhov
--moist equil 
--rad gray 
--microphy 0M 
--turbconv edmf 
--job_id longrun_sphere_aquaplanet_rhoe_equilmoist_gray_edmf_highres_ft64 
--skip_tc_hydro_balance true
--dt 1secs 
--t_end 1day 
--z_elem 45 
--dz_bottom 30 
--h_elem 16 
--kappa_4 1e16 
--rayleigh_sponge true 
--alpha_rayleigh_uh 0 
--fps 30 
--dt_save_to_sol 2hours 
--dt_save_to_disk 2hours 
--FLOAT_TYPE Float64`

**Comment by charleskawczynski** [comment]
### EDMF-dycore field unification

  - [x] thermo state #867
  - [x] pressure #875
  - [ ] `ᶜT` No PR yet
  - [ ] `ᶜω³` No PR yet
  - [ ] `ᶜK` No PR yet
  - [ ] `ᶜuvw` No PR yet
  - [ ] `Yₜ`? No PR yet
  - [ ] `ᶠω¹²` No PR yet
  - [ ] `ᶠu¹²` No PR yet
  - [ ] `ᶠu³` No PR yet
  - [ ] `ᶜf` No PR yet
  - [ ] `T_sfc` (would it be easier to change this to `ᶠts_sfc`?) No PR yet

### EDMF-dycore type unification
 - [ ] `EquilibriumMoisture` and `EquilMoistModel`
 - [ ] `NonEquilibriumMoisture` and `NonEquilMoistModel`
This code will need to be added into `src/`, so that edmf and the driver is able to access them from a common scope

### Migrating TC's grid-mean computations
#### Migrate functions in TC's grid-mean computations outside of `init_tc!`
 - [ ] `compute_ref_state!`
 - [ ] `Cases.initialize_profiles`
 - [ ] `set_thermo_state_pθq!`
 - [ ] `set_grid_mean_from_thermo_state!`
 - [ ] `assign_thermo_aux!`
 - [ ] `Cases.initialize_forcing`
 - [ ] `Cases.initialize_radiation`
#### Migrate functions in TC's grid-mean computations outside of `sgs_flux_tendency!`
 - [ ] `set_thermo_state_peq!`
 - [ ] `assign_thermo_aux!`
 - [ ] `get_surface`
 - [ ] `affect_filter!`
 - [ ] `update_forcing`
 - [ ] `update_radiation`
 - [ ] `compute_gm_tendencies!`

**Comment by charleskawczynski** [comment]
We may need to apply temporary patches to `Migrating TC's grid-mean computations` because migrating/integrating all of Cases into the appropriate place is a bit complicated and shouldn't hold us back from making progress for getting things on the sphere

**Comment by trontrytel** [comment]
Not sure if it's helpful regarding our diffusion confusion. But here is a small map of what happens when  `examples/hybrid/driver/jl` calls `sgs_flux_tendency`. @szy21 , @dennisYatunin , @charleskawczynski                       
                                                                                
    -> TCU.sgs_flux_tendency!                                                   
                                                                                
        -> set_thermo_state_peq!                                                
        -> assign_thermo_aux!                                                   
                                                                                
        -> get_surface                                                          
                                                                                
        -> TC.affect_filter!                                                    
                                                                                
        -> TC.update_aux!                                                       
                                                                                
            -> ...                                                              
            -> some additional clipping of edmf vars                            
            -> compute_diffusive_fluxes                                         
                @. diffusive_flux_qt = -ρ_ae_KH * ∇ q_tot_en                    
                @. diffusive_flux_h  = -ρ_ae_KH * ∇ h_tot_en                    
                @. diffusive_flux_uₕ = -ρ_ae_KM * ∇ uₕ_gm                       
                                                                                
        -> TC.compute_precipitation_sink_tendencies                             
        -> TC.compute_precipitation_advection_tendencies                        
                                                                                
        -> TC.compute_turbconv_tendencies!                                      
                                                                                                                    
            -> compute_up_tendencies!                                           
                -> @. tends_ρarea =                                             
                -> @. tends_ρaθ_liq_ice =                                       
                -> @. tends_ρaq_tot =                                           
                -> @. tends_w =                                                 
                                                                                
            -> compute_en_tendencies! tke, hvar, qtvar, hqtcov                  
                -> @. D_env +=                                                  
                -> @. tend_covar =                                              
                                                                                
        -> compute_gm_tendencies! # TODO: incrementally disable this and enable proper grid mean terms
                                                                                
            -> @. tendencies_gm_uₕ -= f × (C12(C123(prog_gm_uₕ)) - C12(C123(aux_gm_uₕ_g)))
                                                                                
            -> @. tendencies_gm.ρe_tot -= subsidence                            
            -> @. tendencies_gm.ρq_tot -= subsidence                            
            -> @. tendencies_gm.ρe_tot += radiation                             
            -> @. tendencies_gm.ρq_tot += LS advaction                          
            -> @. tendencies_gm.ρq_tot += precipitation                         
            -> @. tendencies_gm.ρe_tot += precipitation                         
                                                                                
            -> TC.compute_sgs_flux!                                             
                                                                                
                 -> compute the massflux part (diffusive part is computed in update_aux)
                                                                                
                     -> @. massflux_h  = ρ * a_en   * (w_en   - w_gm) * (h_tot_en   - h_tot_gm) +
                                         ρ * a_up_i * (w_up_i - w_gm) * (h_tot_up_i - h_tot_gm)
                     -> @. massflux_qt = ρ * a_en * (w_en   - w_gm) * (q_tot_en   - q_tot_gm) +
                                         ρ * a_up * (w_up_i - w_gm) * (q_tot_up_i - q_tot_gm)
                                                                                
                 -> @. sgs_flux_h_tot = diffusive_flux_h + massflux_h           
                 -> @. sgs_flux_q_tot = diffusive_flux_qt + massflux_qt         
                 -> @. sgs_flux_uₕ = diffusive_flux_uₕ                          
                                                                                
            -> @. tendencies_gm.ρe_tot += -∇ sgs_flux_h_tot                     
            -> @. tendencies_gm.ρq_tot += -∇ sgs_flux_q_tot                     
            -> @. tendencies_gm_uₕ += -∇ sgs_flux_uₕ / ρ

**Comment by trontrytel** [comment]
You can see there all the `gm` tendencies that @charleskawczynski is trying to move/disable such ad subsidence, radiation and LS advection. Not sure where to put precipitation.

I'm now also wondering if the computation of the massflux could be moved to the update_aux.

And then at the very last is the sgs flux contribution to the `gm`. Not sure how we want to merge that with what is currently done in dycore

**Comment by charleskawczynski** [comment]
My wip for the forcing:

```
#####
##### DYCOMS_RF01 forcing
#####

function forcing_cache(Y, params, ::CA.ForcingDYCOMS_RF01;)
    return (; ᶜdqtdt_hadv = similar(Y.c, FT), ᶜdTdt_hadv = similar(Y.c, FT))
end
function forcing_tendency!(
    Yₜ,
    Y,
    p,
    t,
    colidx,
    forcing::CA.ForcingDYCOMS_RF01,
)
    thermo_params = TCP.thermodynamics_params(param_set)
    T_0 = TCP.T_0(param_set)
    Lv_0 = TCP.LH_v0(param_set)
    aux_gm = TC.center_aux_grid_mean(state)
    cv_v = TCP.cv_v(param_set)
    R_v = TCP.R_v(param_set)
    ᶜT = p.ᶜT[colidx]
    ᶜdqtdt_hadv = p.ᶜdqtdt_hadv[colidx]
    ᶜdTdt_hadv = p.ᶜdTdt_hadv[colidx]
    ᶜts = p.ᶜts[colidx]
    # TODO: should `hv` be a thermo function?
    #     (hv = cv_v * (ᶜT - T_0) + Lv_0 - R_v * T_0)
    @. Y.c.ρe_tot[colidx] +=
        Y.c.ρ[colidx] * (
            TD.cp_m(thermo_params, ᶜts) * ᶜdTdt_hadv +
            (cv_v * (ᶜT - T_0) + Lv_0 - R_v * T_0) *
            ᶜdqtdt_hadv
        )
    return nothing
end
```

**Comment by trontrytel** [comment]
Looks good to me. I can help with the docstrings so that we have links to correct paper paragraphs that define those individual forcings.

**Comment by charleskawczynski** [comment]
I forget when it got merged, but we now have an explicit edmf on a sphere job. Closing.

**Comment by trontrytel** [comment]
I wanted to keep it open untill we figure out the issues at the surface. I think we still can't run with a moist case.

**Comment by charleskawczynski** [comment]
Any updates on this @trontrytel?

**Comment by trontrytel** [comment]
Good question. Seems like I don't have the bandwidth to debug the old EDMF code in the end. But maybe we don't need it, since we are focusing on EDMFX? 

The issue here is that we are running a dry case and not moist:

https://github.com/CliMA/ClimaAtmos.jl/blob/f0ef6126819fe36c5e90b2053c514589a4224892/.buildkite/pipeline.yml#L295-L302

@charleskawczynski - would you be ok to delete that test from the CI and close the SDI? We already have tests that run on the sphere with the new EDMFX

**Comment by szy21** [comment]
@trontrytel @charleskawczynski should we close this? :)
